# Generated by Django 5.0 on 2024-12-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
