# Generated by Django 5.0 on 2025-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=50)),
                ('font_file', models.CharField(max_length=50)),
            ],
        ),
    ]
