# Generated by Django 5.0 on 2025-01-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0003_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonts',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
