# Generated by Django 5.0 on 2025-01-10 12:31

import certifier_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0004_fonts_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=0)),
                ('folder_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent_folder', to='certifier_app.folders')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=certifier_app.models.Files.user_directory_path)),
                ('is_deleted', models.BooleanField(default=0)),
                ('file_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='certifier_app.folders')),
            ],
        ),
    ]
