# Generated by Django 5.0 on 2025-01-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0005_folders_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='certifier_app.folders'),
        ),
    ]
