# Generated by Django 5.0 on 2025-01-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0006_alter_files_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_name',
        ),
    ]
