# Generated by Django 5.0 on 2025-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0007_remove_files_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_starred',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='folders',
            name='is_starred',
            field=models.BooleanField(default=0),
        ),
    ]
