# Generated by Django 5.0 on 2025-01-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0009_files_created_datetime_folders_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
