# Generated by Django 5.0 on 2025-01-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0012_alter_files_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_folder', to='certifier_app.folders'),
        ),
    ]
