# Generated by Django 5.0 on 2025-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0013_alter_folders_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
