# Generated by Django 5.0 on 2025-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0014_files_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
