# Generated by Django 5.0 on 2025-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0015_alter_files_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_permanently_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='quickly_accessible',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='folders',
            name='is_permanently_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='folders',
            name='quickly_accessible',
            field=models.BooleanField(default=0),
        ),
    ]
