# Generated by Django 5.0 on 2025-01-12 19:54

import certifier_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier_app', '0016_files_is_permanently_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=certifier_app.models.Files.user_directory_path),
        ),
    ]
